project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - icon: pencil-square
        text: "Overview"
        menu:
          - text: "Proposal"
            href: "Overview/Proposal.html"
          - text: "Overview"
            href: "Overview/Overview.html"
      - text: "Task"
        menu:
          - text: "Task Information"
            href: "Task/Info.html"
          - text: "Code"
            href: "Task/combined.html"
      - icon: book-half
        text: "Meeting Minutes"
        menu:
          - text: "Meeting Minutes 1"
            href: "MeetingMinutes/MeetingMinutes1.html"
          - text: "Meeting Minutes 2"
            href: "MeetingMinutes/MeetingMinutes2.html"
          - text: "Meeting Minutes 3"
            href: "MeetingMinutes/MeetingMinutes3.html"
          - text: "Meeting Minutes 4"
            href: "MeetingMinutes/MeetingMinutes4.html"
      - text: "Shiny App"
        href: "ShinyApp.html"
      - text: "Poster"
        href: "Poster.html"

      

    right:
      - href: about.qmd
        text: About
    
    tools:       
    - icon: github         
      href: https://github.com/lnealicia/ISSS608-G2

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

