project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - icon: pencil-square
        text: "Proposal"
        menu:
          - text: "Proposal"
            href: "Proposal/Proposal.html"
          - text: "Overview"
            href: "overview.html"
      - text: "Task Questions"
        menu:
          - text: "Task Information"
            href: "Task/Info.html"
          - text: "Overview"
            href: "Task/combined.html"
          - text: "Data Preprocessing"
            href: "Task/DataPreprocessing.html"
          - text: "Q1"
            href: "Task/Q1.html"
          - text: "Q2"
            href: "Task/Q2.html"
          - text: "Q3"
            href: "Task/Q3.html"
          - text: "Q4"
            href: "Task/Q4.html"
      - icon: book-half
        text: "Meeting Minutes"
        menu:
          - text: "Meeting Minutes 1"
            href: "MeetingMinutes/MeetingMinutes1.html"
          - text: "Meeting Minutes 2"
            href: "MeetingMinutes/MeetingMinutes2.html"
          - text: "Meeting Minutes 3"
            href: "MeetingMinutes/MeetingMinutes3.html"
      - text: "Shiny App"
        href: "ShinyApp.html"
      - text: "Poster"
        href: "Poster.html"

      

    right:
      - href: about.qmd
        text: About
    
    tools:       
    - icon: github         
      href: https://github.com/lnealicia/ISSS608-G2

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

