project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - icon: pencil-square
        text: "Proposal"
        menu:
          - text: "Proposal"
            href: "Proposal/Proposal.html"
      - icon: book-half
        text: "Meeting Minutes"
        menu:
          - text: "Meeting Minutes 1"
            href: "MeetingMinutes1.html"

    right:
      - href: about.qmd
        text: About
    
    tools:       
    - icon: github         
      href: https://github.com/lnealicia/ISSS608-G2

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

editor: visual

