---
title: "Meeting Minutes 3"
author: "Group 2"
date: "June 18, 2024"
date-modified: last-modified
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# Meeting Minutes 3

Date: 18 June 2024

Attendance: All present

Proposed Project Timeline:

**Current Status:**

Codes have been combined.

YouTing will start first, while Alicia and Keke complete their exams on 24 June Monday.

**Agenda:**

1.  Discuss the overview and storytelling approach for the project.

2.  Outline the project sections and specific questions to address.

**Discussion Points:**

**Overview and Storytelling:**

-   The project will be structured to clearly narrate the impact and findings from our analysis.

-   Key sections identified for the report: preprocessing, solving four key questions, analysis and conclusion.

**Sections Breakdown:**

**1. Preprocessing:**

-   Discussed the steps necessary for cleaning and organizing the data to ensure accurate analysis.

**2. Solving Four Questions:**

-   **Q1. Corporate Structure, Active Influences:**

    -   Objective: Identify all active nodes within the corporate structure.

-   **Q2. Atypical/Typical Transactions (B2B):**

    -   Objective: Determine atypical nodes and edges by analyzing business-to-business transactions.

-   **Q3. Network / Ownership Analysis (person2person):**

    -   Objective: Identify the most influential person nodes within the network.

-   **Q4. Impact of SouthSeafood Corp Closure:**

    -   Objective: Analyze the impact of SouthSeafood Express Corp's closure, identifying potential accomplices, competitors, and other suspicious transactions.

**3. Analysis:**

-   Integrate conclusions from each question to uncover overlaps between the nodes of Q1 and Q4.

-   Compare results from Q1-Q4 to identify individuals or entities that repeatedly appear, suggesting they may be suspicious and should be monitored closely.

### Next Steps (19 June - 25 June)

-   **Combine preprocessing code**: Integrate all preprocessing steps into a single file (`preprocessing.qmd`) and standardize all variable names.

-   **Create plots for each question**: Use ShinyApp to generate visualizations for each question and annotate with corresponding findings.

-   **Integrate findings**: Synthesize results and draw comprehensive conclusions from overlapping data.

### Action Items:

-   **Youting**: Lead preprocessing efforts, ensuring data is clean, organized, and variables are standardized. And plot for Q2.

-   **Alicia**: Plot results for Q1, analyze, draw conclusions and design poster.

-   **Keke**: Plot results for Q3 and Q4, analyze, and draw conclusions.

-   **Schedule next meeting**: Plan a follow-up meeting on 25 June to review initial findings and integrate results for the analysis section.

**Deadlines:**

26 June - Poster Due

29 June - Project Submission (website, Shiny app, report)

29 June - Poster Presentation
